/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapFileGUI.java
 *
 * Created on Jun 3, 2011, 8:01:40 AM
 */

package client;

import javax.swing.tree.*;
import javax.swing.*;

/**
 *
 * @author Mike
 */
public class MapFileGUI extends javax.swing.JDialog {

    private ClientGUI client;
    private String map;

    /** Creates new form MapFileGUI */
    public MapFileGUI(String map, ClientGUI client, boolean modal) {
        super(client, modal);
        initComponents();

        this.setTitle("Map for " + map);
        this.client = client;
        this.map = map;
        this.spTree.setViewportView(client.getSrcTree());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        spTree = new javax.swing.JScrollPane();
        btOK = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTree, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(btOK)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spTree, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        TreePath path = this.client.getSrcTree().getSelectionPath();

        if (path == null)
        {
            JOptionPane.showMessageDialog(null,
                "Error: You must select a map destination.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (path != null)
        {
            DefaultMutableTreeNode node =
                    (DefaultMutableTreeNode)path.getLastPathComponent();

            ProjFile srcNode = (ProjFile)node.getUserObject();

            srcNode.setRemoteFileMap(this.map);

            this.dispose();
        }
    }//GEN-LAST:event_btOKActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.client.getSrcScrollPane().setViewportView(client.getSrcTree());
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JScrollPane spTree;
    // End of variables declaration//GEN-END:variables

}
