/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewFileGUI.java
 *
 * Created on May 5, 2011, 2:27:55 PM
 */

package client;

import javax.swing.*;
import java.io.*;
import javax.swing.tree.*;

/**
 *
 * @author Mike
 */
public class NewPackageGUI extends javax.swing.JDialog {

    private String path;
    private ProjTreePopup popup;

    /** Creates new form NewFileGUI */
    public NewPackageGUI(java.awt.Frame parent, boolean modal, String path,
                        ProjTreePopup popup)
    {
        super(parent, modal);
        initComponents();

        this.path = path;
        this.popup = popup;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Package");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Name:");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (this.txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "Error: Name is invalid.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            this.popup.setNodeName("");
            return;
        }        
        
        DefaultMutableTreeNode node = this.popup.getNode();
        int i;
        for (i = 0; i < node.getChildCount(); i++)
        {
            ProjFile srcNode = 
                    (ProjFile)((DefaultMutableTreeNode)node.getChildAt(i)).
                    getUserObject();
            
            if (srcNode.getText().equals(this.txtName.getText()))
                break;            
        }


        if (i < node.getChildCount()) {
            JOptionPane.showMessageDialog(null,
                    "Error: Package already exists.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            this.popup.setNodeName("");
            return;
        }

        String dirStr = this.path + "\\" + this.txtName.getText();

        try
        {
            new File(dirStr).mkdir();
        }
        catch (Exception e)
        {
            System.err.println("Error: " + e.getMessage());
        }

        this.popup.setNodeName(dirStr);

        this.setVisible(false);
}//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.popup.setNodeName("");
        this.setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.popup.setName("");
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
